# Generated by Django 6.0.5 on 2026-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='platform',
            field=models.CharField(choices=[('X', 'X Platform'), ('FB', 'Facebook')], default='X', max_length=50),
        ),
    ]
