# Generated by Django 5.1.15 on 2026-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='current_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LUNCH', 'Lunch Break'), ('SHORT_BREAK', 'Short Break'), ('LEAVING', 'Leaving for the Day'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
