# Generated by Django 5.1.15 on 2026-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LUNCH', 'Lunch Break'), ('SHORT_BREAK', 'Short Break'), ('PRAYER_BREAK', 'Prayer Break'), ('MEETING', 'Meeting'), ('LEAVING', 'Leaving for the Day'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20),
        ),
    ]
