# Generated by Django 5.1.15 on 2026-07-06 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoutingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('LANGUAGE', 'Language'), ('CHANNEL', 'Channel'), ('REQUEST_TYPE', 'Request Type')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routing_attributes',
                'unique_together': {('attribute_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(related_name='supervisor_scopes', to='accounts.routingattribute')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supervisor_scopes', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_scope', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supervisor_scopes',
            },
        ),
        migrations.CreateModel(
            name='RoutingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(related_name='routing_groups', to='accounts.routingattribute')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_routing_groups', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='routing_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routing_groups',
                'unique_together': {('supervisor', 'name')},
            },
        ),
    ]
