# Generated by Django 6.0.5 on 2026-05-12 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('DM', 'Direct Message'), ('MENTION', 'Mention'), ('POST_REPLY', 'Post Reply')], max_length=50)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('final_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('AI_REVIEW', 'AI Review'), ('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed')], default='NEW', max_length=50)),
                ('is_auto_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='customers.customer')),
            ],
        ),
    ]
