# Generated by Django 6.0.5 on 2026-05-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='category',
            field=models.TextField(blank=True, default='Overcharge', null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='engagement',
            name='sla',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
