# Generated by Django 6.0.5 on 2026-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_engagement_category_engagement_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='sla',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
