# Generated by Django 6.0.5 on 2026-05-18 10:59

from django.db import migrations, models


def populate_request_numbers(apps, schema_editor):
    Engagement = apps.get_model('engagements', 'Engagement')

    for engagement in Engagement.objects.filter(request_number__isnull=True):
        engagement.request_number = f'REQ{engagement.pk:04d}'
        engagement.save(update_fields=['request_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_alter_engagement_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='request_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.RunPython(
            populate_request_numbers,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='engagement',
            name='request_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
