# Generated by Django 6.0.5 on 2026-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0004_engagement_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='category',
            field=models.CharField(blank=True, choices=[('Overcharge', 'Overcharge'), ('Billing', 'Billing'), ('Refund', 'Refund'), ('Technical Issue', 'Technical Issue'), ('Account Support', 'Account Support'), ('Complaint', 'Complaint'), ('General Inquiry', 'General Inquiry')], default='Overcharge', max_length=50, null=True),
        ),
    ]
