# Generated by Django 5.1.15 on 2026-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="channels",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
